### ISSUE TITLE
just-use-8 -> Bag-of-Bytes

### ISSUE THREAD

**Issue by indolering** [nicowilliams/ietf-fs-i18n#3]
The mailing list universally disliked the "just-use-8" and "just-use-16" terminology, adding a definition at the top doesn't really help.  Why don't you just the standard Bag-of-Bytes vernacular?  

> Windows and Unix-like operating systems are generally adopt a Bag-of-Bytes approach, treating filenames as arrays containing arbitrary 16-bit or 8-bit values....

**Comment by nicowilliams** [comment]
`just-use-N` is the terminology that we use in the KITTEN WG, and also in the now-concluded KRB-WG.  It turns out we don't all speak the same technical language; that's OK.  I really like the `just-use-N` formulation as it really drives the point across quite clearly: the implementation doesn't check for UTF validity.  Some of those who objected accepted having a glossary entry for that term.

`bag-of-bytes` might work for `char *`, but not for `uint16_t *` or `wchar_t`.  `bag-of-code-units` might work better.  But that's so much more verbose than `just-use-N`.  Also, `just-use-N` harkens back to `8-bit clean`, which was a very common term for a long time.

**Comment by nicowilliams** [comment]
Also, because `just-use-16` is a thing, I'd rather work to get `just-use-N` accepted as terms.

**Comment by indolering** [comment]
I don't know what to say, no one on the mailing list liked it and the only mention of it I can [find on Google](https://www.google.com/search?q=%22just-use-8%22) is the IETF draft, some four pages in.  In the various technical documents I have written up, I use Bag-of-Bytes without referring to 16-bit-codepoints.

**Comment by nicowilliams** [comment]
This is not a big deal, and a bit of bikeshedding. Let's defer.
